### ISSUE TITLE
cross platform solution for rand at CT (avoidining 'dummy seed' of windows and other cross platform issues)

### ISSUE THREAD

**Issue by timotheecour** [OpenSystemsLab/tempfile.nim#12]
/cc @ba0f3

potential cross platform solution for rand at CT (avoidining 'dummy seed' of windows and other cross platform issues):

* make `nimble install tempfile` installs a binary (these go automatically in ~/.nimble/bin IIRC, on posix), say, tempfile_helper
this binary returns the seed `random.randomize()` (which we can improve later, independently), or a custom proc, and prints its value
* call it at CT using `gorgeEx` (let's say we can assume it's in PATH, or maybe allow passing a string in API to specify path to bin containing it)

## note
* this would fix https://github.com/OpenSystemsLab/tempfile.nim/issues/11
* this would fix windows case at CT (currently not really working because of `dummy seed`)
* this would be more robust than relying on `date +'%N'` , and allow making it further more random by allowing to use pid and threadid, all in a clean way using pure nim code

**Comment by ba0f3** [comment]
too bad, `getpid`  proc and times module does not work on compile time.

**Comment by ba0f3** [comment]
problem will be resolved once this PR get merged https://github.com/nim-lang/Nim/pull/9851, refs nim-lang/Nim#8588

here is an example for getting random seed at compile time
```nim
import random

proc seeder() = discard
proc getSeed(p: pointer): int =
  cast[int](p)

proc test(): int {.compileTime.} =
  var
    seed = getSeed(seeder)
    r = initRand(seed)

  for i in 1..10:
    echo r.rand(int.high)

discard test()
```

**Comment by ba0f3** [comment]
shorter version
```nim
import random
proc getRandSeed(): int {.compileTime.} =
  var a: int
  cast[int](pointer(addr a))

proc test(): int {.compileTime.} =
  var r = initRand(getRandSeed())
  for i in 1..10:
    echo rand(r, int.high)
discard test()
