### ISSUE TITLE
mkdtemp should not return pre-existing directories

### ISSUE THREAD

**Issue by nigredo-tori** [OpenSystemsLab/tempfile.nim#5]
Current `mkdtemp` implementation does not check directory for existence. This means that it is entirely possible to receive a "temporary" directory that is being used by some other code.
To check that it is, indeed, possible, try adding `len` of 0 at [line 60](https://github.com/OpenSystemsLab/tempfile.nim/blob/9416fc6da11db0323bb958d10243e455b6be07e6/tempfile.nim#L60) and calling `mkdtemp` two times.
The reason for this is the behavior of `createDir` function - it does not fail if the directory already exists.
I don't see a non-racy way to fix this without delving into platform-specific code, so for now I propose checking `existsDir` before `createDir`.

**Comment by ba0f3** [comment]
merged, thanks
