### ISSUE TITLE
Insecure file creation

### ISSUE THREAD

**Issue by FedericoCeratto** [OpenSystemsLab/tempfile.nim#8]
Hi,
It appears that the creation of a temp file can open an already existing file in:
https://github.com/OpenSystemsLab/tempfile.nim/blob/master/tempfile.nim#L43

**Comment by ba0f3** [comment]
thank you, I will fix it as soon as I have spare time

**Comment by ba0f3** [comment]
`mktemp` proc already check for exists file, so this wont happens
