### ISSUE TITLE
doesn't work at compile time

### ISSUE THREAD

**Issue by timotheecour** [OpenSystemsLab/tempfile.nim#9]
a few issues:
* mkstemp can't be used because we can't fopen a file at CT
* mktemp can be used but is marked deprecated, however:
* `existsFile` can't be used at CT
* the random name returned at CT is "FFFFFFFF", ie not random

## other points
* why mark mktemp as deprecated given that it's used by mkstemp?
* sounds like a nim bug: how come nim doesn't show deprecation msg when using mkstemp given that it uses mktemp which itself is deprecated? 
EDIT: filed https://github.com/nim-lang/Nim/issues/9854

## potential solution
on posix: use mktemp + gorgeEx (ie execute shell cmd at CT)
on windows: ?

## eg use case:
https://github.com/genotrance/nimterop/pull/27 where I need a rand file at CT

**Comment by ba0f3** [comment]
`mktemp` marked as deprecated because of  no real file created, it may causes security issues, I will make it private soon.

I will take a look on CT when I have spare time. Thank you!

**Comment by timotheecour** [comment]
>  it may causes security issues, I will make it private soon.

meh, then just call it `mktempUnsafe` to make it clear to users; but there are useful use cases (where security is not a concern) for returning a path to a not-yet-created file (even if it could theoretically fail in adversarial circumstances); nim is a systems programming language, so should allow that IMO

**Comment by ba0f3** [comment]
greate idea,  I will make some changes soon
